services:
  - type: web
    name: elderly-monitoring-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    workingDir: server/django_backend
    envVars:
      - key: DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        value: elderly_monitoring_django_secret_2026