from django.urls import path
from . import views

urlpatterns = [
    path("auth/login", views.login),
    path("auth/logout", views.logout),
    path("auth/current", views.current_user),
    path("auth/permissions", views.permissions),
    path("elderly/list", views.elderly_list),
    path("elderly/create", views.elderly_create),
    path("elderly/health-data", views.create_health_data),
    path("elderly/<int:elderly_id>", views.elderly_item),
    path("elderly/<int:elderly_id>/contacts", views.elderly_contacts),
    path("elderly/<int:elderly_id>/communications", views.elderly_communications),
    path("alerts/list", views.alerts_list),
    path("alerts/statistics", views.alerts_statistics),
    path("alerts/create", views.alerts_create),
    path("alerts/triage", views.alerts_triage),
    path("alerts/<int:alert_id>/handle", views.alerts_handle),
    path("alerts/<int:alert_id>/workflow", views.alerts_workflow),
    path("orders/list", views.orders_list),
    path("orders/create", views.orders_create),
    path("orders/<int:order_id>/status", views.orders_update_status),
    path("orders/<int:order_id>/complete", views.orders_complete),
    path("devices/list", views.devices_list),
    path("devices/statistics", views.devices_statistics),
    path("devices/create", views.devices_create),
    path("devices/<int:device_id>/status", views.devices_update_status),
    path("devices/<int:device_id>/telemetry", views.devices_telemetry),
    path("devices/<int:device_id>", views.devices_item),
    path("doctors/list", views.doctors_list),
    path("doctors/create", views.doctors_create),
    path("doctors/<int:doctor_id>/status", views.doctors_update_status),
    path("doctors/<int:doctor_id>", views.doctors_item),
    path("visits/list", views.visits_list),
    path("visits/create", views.visits_create),
    path("visits/<int:visit_id>/complete", views.visits_complete),
    path("dashboard/overview", views.dashboard_overview),
    path("dashboard/trend", views.dashboard_trend),
    path("reports/overview", views.reports_overview),
    path("reports/export/csv", views.reports_export_csv),
    path("reports/export/print", views.reports_export_print),
    path("reports/export/ledger", views.reports_community_ledger),
    path("settings/current", views.settings_current),
    path("notifications/list", views.notifications_list),
    path("events/trace", views.events_trace),
    path("db/schema", views.db_schema),
    path("db/table-preview", views.db_table_preview),
    path("ai/risk", views.ai_risk),
    path("ai/diagnosis", views.ai_diagnosis),
]
